"""add language to posts

Revision ID: 4c81cb837fd9
Revises: 89ff22c2e3c0
Create Date: 2018-12-11 08:29:52.862748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c81cb837fd9'
down_revision = '89ff22c2e3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
